### ISSUE TITLE
Please update documentation

### ISSUE THREAD

**Issue by nousernameavailableanymore** [greater-than/Obsidian-Tracker-Plus#25]
How do I use the aspect ratio that was introduced in the latest version?
Where can I find documentation for that?

That being said, after switching from "Tracker" to "Tracker+", my previous chart would not render anymore (fixed after restart).
I tried to find out if the name of the codeblock had changed and I was not even able to find the first and basic step described anywhere that you had to create a codeblock of type "tracker".

If I had not used "tracker" before, I would have instantly uninstalled again, as the documentation did not show on the first page, how to get started...

**Comment by greater-than** [comment]
@nousernameavailableanymore Thank you for posting this issue.

The changes that were included from PRs in the original tracker plugin were tested with limited use-cases. Could you provide a sample of the code block that is not working for you?

**Comment by nousernameavailableanymore** [comment]
@greater-than 
The codeblock worked fine again after restarting Obsidian.

However, I could not find documentation on how to change the aspect ratio of charts.
This is the main "issue" here.
The latest release notes mention that this feature was added but do not describe how to use it.

**Comment by greater-than** [comment]
Gotcha. I'll post an update to the documentation shortly

**Comment by greater-than** [comment]
I'm working on an update to the docs now, but in the meantime, here's an example of how to use the aspectRatio:
```
```tracker
searchType: tag
searchTarget: exercise-pushup
folder: diary
endDate: 2021-01-31
aspectRatio: 4:3
line:
    title: PushUp
    yAxisLabel: Count
    lineColor: "#d65d0e"
 ```
